
const btn0 = document.getElementById('0');
const btn1 = document.getElementById('1');
const btn2 = document.getElementById('2');
const btn3 = document.getElementById('3');
const btn4 = document.getElementById('4');
const btn5 = document.getElementById('5');
const btn6 = document.getElementById('6');
const btn7 = document.getElementById('7');
const btn8 = document.getElementById('8');
const btn9 = document.getElementById('9');
const btndot = document.getElementById('.');
const btnpos_neg = document.getElementById('+/-');
const btnadd = document.getElementById('+');
const btnsub = document.getElementById('-');
const btntimes = document.getElementById('*');
const btndiv = document.getElementById('/');
const btnequal = document.getElementById('=');;
const btnclear = document.getElementById('C');

let input = ''; 
let result = '';

btn0.addEventListener('click', addnumber.bind(null,'0'));
btn1.addEventListener('click', addnumber.bind(null,'1'));
btn2.addEventListener('click', addnumber.bind(null,'2'));
btn3.addEventListener('click', addnumber.bind(null,'3'));
btn4.addEventListener('click', addnumber.bind(null,'4'));
btn5.addEventListener('click', addnumber.bind(null,'5'));
btn6.addEventListener('click', addnumber.bind(null,'6'));
btn7.addEventListener('click', addnumber.bind(null,'7'));
btn8.addEventListener('click', addnumber.bind(null,'8'));
btn9.addEventListener('click', addnumber.bind(null,'9'));
btndot.addEventListener('click',adddecimal.bind(null,'.'));
btnpos_neg.addEventListener('click', PostiveOrNegative);
btnadd.addEventListener('click', addoperator.bind(null,'+'));
btnsub.addEventListener('click', addoperator.bind(null,'-'));
btntimes.addEventListener('click', addoperator.bind(null,'*'));
btndiv.addEventListener('click', addoperator.bind(null,'/'));
btnequal.addEventListener('click', calculate);
btnclear.addEventListener('click', cleardisplay);
